#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-trove4j
Version  : 1.0.20181211
Release  : 1
URL      : https://repo1.maven.org/maven2/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211-sources.jar
Source0  : https://repo1.maven.org/maven2/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211-sources.jar
Source1  : https://repo1.maven.org/maven2/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211.jar
Source2  : https://repo1.maven.org/maven2/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: mvn-trove4j-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-trove4j package.
Group: Data

%description data
data components for the mvn-trove4j package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/intellij/deps/trove4j/1.0.20181211
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/intellij/deps/trove4j/1.0.20181211
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/intellij/deps/trove4j/1.0.20181211
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211-sources.jar
/usr/share/java/.m2/repository/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211.jar
/usr/share/java/.m2/repository/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211.pom
